name: Build Project

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install conan

      - name: Build
        run: sh build.sh

      - name: Save build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compiled-binaries
          path: |
            build/Reader
            build/RawReader
          if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: compiled-binaries

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            Release for version ${{ github.ref }}
          files: |
            Reader
            RawReader
